//! Gmail summary notification channel
//!
//! Sends notifications via Gmail's API (or SMTP relay).
//! Configured via environment variables:
//! - `CARPAI_GMAIL_FROM` — Sender email address
//! - `CARPAI_GMAIL_TO` — Recipient email address
//! - `CARPAI_GMAIL_APP_PASSWORD` — Gmail App Password (for SMTP)

use std::env;
use tracing::{info, warn};

/// Error type for Gmail notification operations
#[derive(Debug, thiserror::Error)]
pub enum GmailError {
    #[error("Not configured: missing Gmail environment variables")]
    NotConfigured,
    #[error("SMTP would be used: {0}")]
    SmtpUnavailable(String),
    #[error("Template error: {0}")]
    TemplateError(String),
}

/// Gmail notifier that generates email summaries
pub struct GmailNotifier {
    from: String,
    to: String,
}

impl GmailNotifier {
    /// Create a new Gmail notifier from environment variables
    pub fn from_env() -> Result<Self, GmailError> {
        let from = env::var("CARPAI_GMAIL_FROM")
            .map_err(|_| GmailError::NotConfigured)?;
        let to = env::var("CARPAI_GMAIL_TO")
            .map_err(|_| GmailError::NotConfigured)?;

        Ok(Self { from, to })
    }

    /// Create a new Gmail notifier with explicit addresses
    pub fn new(from: String, to: String) -> Self {
        Self { from, to }
    }

    /// Send a summary email
    ///
    /// Note: This implementation generates the email template and logs it.
    /// Actual SMTP delivery requires the `lettre` crate (add when needed).
    pub async fn send_summary(&self, subject: &str, body: &str) -> Result<(), GmailError> {
        let email_preview = format!(
            "--- Email Summary ---\n\
             From: {}\n\
             To: {}\n\
             Subject: {}\n\
             \n\
             {}\n\
             --------------------",
            self.from, self.to, subject, body
        );

        info!(
            from = %self.from,
            to = %self.to,
            subject = %subject,
            body_len = body.len(),
            "Generated email summary"
        );

        // Log the email (actual SMTP delivery is a future enhancement)
        warn!(
            "Gmail SMTP delivery not yet implemented — email logged instead.\n\
             To enable SMTP, add `lettre` crate and implement send_via_smtp().\n\
             \n\
             {}",
            email_preview
        );

        Ok(())
    }

    /// Format a session summary into an email body
    pub fn format_session_summary(
        &self,
        session_title: &str,
        message_count: usize,
        token_count: usize,
        duration: std::time::Duration,
    ) -> String {
        format!(
            "## Session Summary\n\n\
             **Title:** {}\n\
             **Messages:** {}\n\
             **Tokens Used:** ~{}\n\
             **Duration:** {:.2}s\n\n\
             _Generated by CarpAI_",
            session_title,
            message_count,
            token_count,
            duration.as_secs_f64()
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_from_env_without_vars() {
        let result = GmailNotifier::from_env();
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), GmailError::NotConfigured));
    }

    #[test]
    fn test_format_session_summary() {
        let notifier = GmailNotifier::new("bot@example.com".into(), "user@example.com".into());
        let summary = notifier.format_session_summary(
            "Code Review",
            12,
            4500,
            std::time::Duration::from_secs(32),
        );
        assert!(summary.contains("Code Review"));
        assert!(summary.contains("12"));
        assert!(summary.contains("4500"));
    }
}
