use crate::nlp::types::*;
use crate::nlp::{DependencyInfo};
use crate::nlp::generate_dependencies;

pub fn generate_architecture_doc(analysis: &NlpAnalysisResult) -> String {
    format!(
        r#"# Architecture Design Document

## 1. Overview

### 1.1 Project Summary
- **Name**: {}
- **Type**: {:?}
- **Complexity**: {:?}
- **Estimated Effort**: {:?} days

### 1.2 Goals and Objectives
Based on the original requirement:
> {}

### 1.3 Scope
**In Scope:**
- Core functionality implementation
- Unit tests and documentation
- Error handling and logging

**Out of Scope:**
- UI/UX design (unless specified)
- Production deployment setup
- Performance optimization (initially)

---

## 2. System Architecture

### 2.1 High-Level Architecture
```
+-----------------------------------------+
|              Client Layer              |
+-----------------------------------------+
|             API Gateway               |
+-----------------------------------------+
|           Business Logic                |
+-----------------------------------------+
|           Data Access Layer             |
+-----------------------------------------+
```

### 2.2 Component Diagram
[TBD - Based on specific requirements]

---

## 3. Technology Stack

### 3.1 Languages and Runtimes
{}

### 3.2 Frameworks and Libraries
{}

### 3.3 Infrastructure
- **Database**: TBD
- **Cache**: TBD
- **Message Queue**: TBD (if needed)

---

## 4. Data Model

### 4.1 Entity Relationship Diagram
[TBD]

### 4.2 Data Flow
[TBD]

---

## 5. API Design

### 5.1 Endpoints
[TBD]

### 5.2 Request/Response Models
[TBD]

---

## 6. Security Considerations

### 6.1 Authentication
[TBD]

### 6.2 Authorization
[TBD]

### 6.3 Data Protection
[TBD]

---

## 7. Non-Functional Requirements

### 7.1 Performance
- Response time: < X ms (P95)
- Throughput: X req/s
- Availability: 99.9%

### 7.2 Scalability
- Horizontal scaling support
- Connection pooling

### 7.3 Reliability
- Error handling
- Retry mechanisms
- Circuit breakers

---

## 8. Testing Strategy

### 8.1 Unit Tests
- Coverage target: > 80%
- Framework: [based on language]

### 8.2 Integration Tests
- API contract tests
- Database integration tests

### 8.3 E2E Tests
- Critical user journeys

---

## 9. Deployment

### 9.1 Environment Setup
- Development
- Staging
- Production

### 9.2 CI/CD Pipeline
- Build
- Test
- Deploy

---

## 10. Monitoring and Observability

### 10.1 Logging
- Structured logging
- Log levels and formats

### 10.2 Metrics
- Business metrics
- Technical metrics

### 10.3 Alerting
- Threshold-based alerts
- On-call procedures

---

*Document generated by CarpAI NLP Engine*
*Last updated: {}*
"#,
        analysis.key_concepts.first().unwrap_or(&"Project".to_string()),
        analysis.classification,
        analysis.complexity.level,
        analysis.complexity.estimated_effort_days,
        analysis.original_text.chars().take(300).collect::<String>(),
        format_tech_stack_list(&analysis.inferred_tech_stack),
        format_tech_stack_list(&analysis.inferred_tech_stack),
        chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string()
    )
}

pub fn generate_components_doc(analysis: &NlpAnalysisResult) -> String {
    format!(
        r#"# Component Design Document

## Component Overview

This document details the components identified during architecture design.

---

## Component List

### 1. Core Components

#### 1.1 Main Application
- **Purpose**: {}
- **Responsibilities**:
  - Entry point coordination
  - Configuration management
  - Lifecycle management
- **Dependencies**: [TBD]
- **Interfaces**: [TBD]

---

## Component Interactions

### Interaction Diagram
```
[Component A] -> [Component B] -> [Component C]
       ^                  v
   [Component D] <- [Component E]
```

---

## Interface Definitions

### APIs
[TBD - Define component interfaces]

### Events
[TBD - Define event contracts]

---

## Data Contracts

### Internal Models
[TBD]

### External Schemas
[TBD]

---

*Generated by CarpAI NLP Engine*
"#,
        analysis.key_concepts.first().unwrap_or(&"System".to_string())
    )
}

pub fn generate_migration_plan(_analysis: &NlpAnalysisResult, source: &SourceSystemInfo, target_lang: &str) -> String {
    format!(
        r#"# Migration Plan: {:?} -> {}

## Executive Summary

This document outlines the migration strategy from {:?} to {}.

### Current State Analysis
- **Source Language**: {:?}
- **Source Framework**: {:?}
- **Estimated LOC**: ~{} lines
- **Technical Debt Score**: {}/10

### Target State
- **Target Language**: {}
- **Target Framework**: {:?}
- **Expected Benefits**:
  - Performance improvement: ~{:.0}%
  - Maintainability improvement: ~{:.0}%
  - Modern ecosystem access: ✅

---

## 1. Migration Strategy

### 1.1 Approach: {}
Options considered:
- Big Bang (all at once): ❌ Too risky
- Strangler (incremental): ✅ Recommended
- Parallel running: ⚠️ Possible but complex

### 1.2 Timeline
- Phase 1: Foundation ({:?} weeks)
- Phase 2: Core migration ({:?} weeks)
- Phase 3: Cleanup and optimization ({:?} weeks)

---

## 2. Pre-Migration Checklist

### 2.1 Assessment
- [ ] Code inventory complete
- [ ] Dependency mapping done
- [ ] Risk assessment finished
- [ ] Team training scheduled

### 2.2 Preparation
- [ ] CI/CD pipeline ready for target
- [ ] Development environment setup
- [ ] Rollback plan documented
- [ ] Monitoring in place

---

## 3. Detailed Migration Steps

### Phase 1: Foundation (Week 1-2)

#### 3.1 Project Structure Setup
```
target-lang-project/
+-- src/
+-- tests/
+-- migrations/
+-- docs/
```

#### 3.2 Shared Infrastructure
- [ ] Create base configuration
- [ ] Set up dependency injection
- [ ] Implement logging framework
- [ ] Add health checks

---

### Phase 2: Core Migration (Week 3-6)

#### 3.3 Data Access Layer
**Mapping:**
| Source | Target | Notes |
|--------|--------|-------|
| DbContext | Repository | Use Repository pattern |
| Entity Framework | ORM | Choose appropriate ORM |

**Tasks:**
- [ ] Create model definitions
- [ ] Implement repository interfaces
- [ ] Set up database context
- [ ] Write data migration scripts

#### 3.4 Business Logic Layer
**Key transformations:**
- Sync -> Async
- Exceptions -> Results<T>
- Manual DI -> Container

**Tasks:**
- [ ] Convert service classes
- [ ] Update method signatures
- [ ] Implement new patterns
- [ ] Write unit tests

#### 3.5 API Layer
**Changes:**
- Controllers -> Handlers/Endpoints
- Attribute routing -> Method routing
- ActionResult -> Response types

**Tasks:**
- [ ] Set up web framework
- [ ] Create endpoint definitions
- [ ] Implement middleware
- [ ] Add input validation

---

### Phase 3: Optimization (Week 7-8)

#### 3.6 Performance Tuning
- [ ] Database query optimization
- [ ] Caching strategy
- [ ] Async operations review
- [ ] Load testing

#### 3.7 Final Cleanup
- [ ] Remove legacy code
- [ ] Update documentation
- [ ] Final testing
- [ ] Performance benchmarking

---

## 4. Risk Mitigation

### 4.1 Technical Risks
| Risk | Probability | Impact | Mitigation |
|------|-----------|--------|------------|
| Data loss | Low | Critical | Backup strategy |
| Downtime | Medium | High | Blue-green deployment |
| Performance regression | Medium | Medium | Load testing |

### 4.2 Operational Risks
- Team learning curve
- Toolchain changes
- Support knowledge gap

---

## 5. Rollback Plan

If migration fails at any point:

1. **During Phase 1**: Simply revert, minimal impact
2. **During Phase 2**: Switch traffic back to legacy system
3. **During Phase 3**: Use feature flags to disable new features

---

## 6. Success Criteria

### 6.1 Functional Parity
- [ ] All features working identically
- [ ] Zero data loss
- [ ] API compatibility maintained

### 6.2 Quality Gates
- [ ] Test coverage ≥ 80%
- [ ] No critical bugs
- [ ] Performance meets baseline or better

### 6.3 Business Metrics
- [ ] User satisfaction stable/improved
- [ ] Support ticket volume manageable

---

## 7. Post-Migration

### 7.1 Knowledge Transfer
- Team training sessions
- Documentation handover
- Best practices guide

### 7.2 Legacy Decommissioning
- Monitor legacy system usage
- Plan shutdown timeline
- Archive artifacts

---

*Migration plan generated by CarpAI NLP Engine*
*Created: {}*
"#,
        source.source_language,
        target_lang,
        source.source_language,
        target_lang,
        source.source_language,
        source.framework.as_deref().unwrap_or("Unknown"),
        source.estimated_loc.unwrap_or(0),
        7, // Placeholder technical debt
        target_lang,
        infer_target_framework(target_lang),
        40.0, // Performance estimate
        60.0, // Maintainability estimate
        "Strangler Fig".to_string(),
        2,
        2,
        4,
        chrono::Local::now().format("%Y-%m-%d").to_string()
    )
}

pub fn extract_source_info_from_analysis(analysis: &NlpAnalysisResult) -> SourceSystemInfo {
    let mut info = SourceSystemInfo {
        source_language: SourceLanguage::Unknown,
        framework: None,
        version: None,
        estimated_loc: None,
        patterns: Vec::new(),
    };
    
    for entity in &analysis.entities {
        match &entity.entity_type {
            EntityType::ProgrammingLanguage => {
                info.source_language = match entity.text.to_lowercase().as_str() {
                    "c#" | ".net" => SourceLanguage::CSharpDotNet,
                    "java" => SourceLanguage::Java,
                    "go" => SourceLanguage::Go,
                    "python" => SourceLanguage::Python,
                    "rust" => SourceLanguage::Rust,
                    "typescript" | "javascript" => SourceLanguage::TypeScriptJavaScript,
                    "c++" | "cpp" => SourceLanguage::Cpp,
                    _ => SourceLanguage::Unknown,
                };
            }
            EntityType::Framework => {
                info.framework = Some(entity.text.clone());
            }
            EntityType::Version => {
                info.version = Some(entity.text.clone());
            }
            _ => {}
        }
    }
    
    info.patterns = analysis.entities.iter()
        .filter(|e| matches!(&e.entity_type, EntityType::Other(_)))
        .map(|e| e.text.clone())
        .collect();
    
    info
}

pub fn generate_mapping_file(source: &SourceSystemInfo, target_lang: &str) -> String {
    format!(
        r#"//! Type Mapping File: {:?} -> {}
//!
//! Auto-generated mapping between type systems
//!
//! Source: {:?} {:?}
//! Target: {}

// ══════════════════════════════════════════════════════
// TYPE MAPPINGS
// ══════════════════════════════════════════════════════

// Primitive Types
pub mod primitives {{
    // Source String -> Target String
    pub fn map_string(s: &str) -> String {{ s.to_string() }}
    
    // Source int -> Target i32/i64
    pub fn map_int(i: i32) -> i32 {{ i }}
    
    // Source bool -> Target bool
    pub fn map_bool(b: bool) -> bool {{ b }}
    
    // Source DateTime -> Target chrono::DateTime<Utc>
    pub fn map_datetime(dt: System::DateTime) -> chrono::DateTime<Utc> {{
        // Implementation depends on target language
        chrono::Utc::now() // placeholder
    }}
}}

// Collection Types
pub mod collections {{
    // Source List<T> -> Target Vec<T>
    pub fn list_to_vec<T>(list: &[T]) -> Vec<T> {{
        list.to_vec()
    }}
    
    // Source Dictionary<K,V> -> Target HashMap<K,V>
    pub fn dict_to_map<K, V>(dict: &[(K, V)]) -> HashMap<K, V> {{
        dict.iter().cloned().collect()
    }}
}}

// Common Patterns
pub mod patterns {{
    // Source try-catch -> Target Result<T,E>
    pub fn try_catch_to_result<T, E>(result: std::result::Result<T, E>) -> Result<T, E> {{
        result.map_err(|e| e) // convert error type
    }}
    
    // Source async/await -> Target async/await
    // (Usually same syntax in modern languages)
    
    // Source null -> Target None/Option
    pub fn null_to_option<T>(value: Option<T>) -> Option<T> {{
        value
    }}
}}

// Framework-Specific Mappings
{}
"#,
        source.source_language,
        target_lang,
        source.source_language,
        source.framework.as_deref().unwrap_or("Unknown"),
        target_lang,
        String::new() // Framework-specific mappings placeholder
    )
}

pub fn generate_target_dependencies(target_lang: &str) -> Vec<DependencyInfo> {
    generate_dependencies(target_lang)
}

pub fn generate_migration_usage_example(target_lang: &str) -> String {
    format!(
        r#"# Migration Usage Example

## Running the Migration

### Step 1: Set up target environment
```bash
# Install target language toolchain
# For {}: see installation guide
```

### Step 2: Run migration tool
```bash
carpai migrate \
    --source ./legacy-code \
    --target {} \
    --plan migration-plan.md
```

### Step 3: Review generated code
```bash
# Check generated files
ls -la src/

# Run tests
cargo test  # or equivalent for target language
```

### Step 4: Validate migration
```bash
# Compare behavior with legacy system
# Run integration tests
# Performance test
```

## Rolling Back (if needed)
```bash
carpai migrate --rollback \
    --last-good-commit abc123
```
"#,
        target_lang,
        target_lang
    )
}

fn format_tech_stack_list(stack: &[TechStackItem]) -> String {
    stack.iter()
        .map(|item| format!("- **{}**: {} (confidence: {:.0})", item.category, item.name, item.confidence))
        .collect::<Vec<_>>()
        .join("\n")
}

fn infer_target_framework(lang: &str) -> String {
    match lang.to_lowercase().as_str() {
        "rust" => "Actix-web / Axum".to_string(),
        "typescript" => "Express / Fastify / NestJS".to_string(),
        "java" => "Spring Boot / Quarkus".to_string(),
        "c++" | "cpp" => "Boost.Asio / Drogon".to_string(),
        "go" | "gin" => "Gin / Echo / Fiber".to_string(),
        _ => "TBD".to_string(),
    }
}

// Helper structs
pub struct SourceSystemInfo {
    pub source_language: SourceLanguage,
    framework: Option<String>,
    version: Option<String>,
    estimated_loc: Option<usize>,
    patterns: Vec<String>,
}

#[derive(Debug, Clone, Copy)]
pub enum SourceLanguage {
    CSharpDotNet,
    Java,
    Go,
    Python,
    Rust,
    TypeScriptJavaScript,
    Cpp,
    Unknown,
}

// Simplified helper implementations