use super::types::*;
use std::collections::HashMap;

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => {
            let upper = first.to_uppercase().collect::<String>();
            format!("{}{}", upper, chars.as_str())
        }
    }
}

/// Generate a Rust project skeleton
pub fn generate_rust_skeleton(analysis: &NlpAnalysisResult) -> String {
    const DEFAULT_CONCEPT: &str = "app";
    let concept = analysis.key_concepts.first().map(|s| s.as_str()).unwrap_or(DEFAULT_CONCEPT);
    let generated_date = chrono::Local::now().format("%Y-%m-%d").to_string();
    let requirements = analysis.original_text.chars().take(150).collect::<String>();
    let concept_cap = capitalize(concept);
    
    format!(
        "// {} - Auto-generated by Carpai NLP Engine\n\
         // Generated at: {}\n\
         //\n\
         // Requirements:\n\
         // {}\n\
         \n\
         /// Main application struct\n\
         struct {} {{\n\
             name: String,\n\
             version: String,\n\
         }}\n\
         \n\
         impl {} {{\n\
             fn new() -> Self {{\n\
                 Self {{\n\
                     name: \"{}\".to_string(),\n\
                     version: \"1.0.0\".to_string(),\n\
                 }}\n\
             }}\n\
             \n\
             fn run(&self) {{\n\
                 println!(\"Starting {}...\");\n\
                 \n\
                 // TODO: Implement based on requirements\n\
                 // Original: {}\n\
             }}\n\
         }}\n\
         \n\
         fn main() {{\n\
             let app = {}::new();\n\
             app.run();\n\
         }}\n",
        concept,
        generated_date,
        requirements,
        concept_cap,
        concept_cap,
        concept,
        concept,
        requirements,
        concept_cap
    )
}

/// Generate a TypeScript project skeleton
pub fn generate_typescript_skeleton(analysis: &NlpAnalysisResult) -> String {
    const DEFAULT_CONCEPT: &str = "solution";
    let concept = analysis.key_concepts.first().map(|s| s.as_str()).unwrap_or(DEFAULT_CONCEPT);
    let generated_date = chrono::Local::now().format("%Y-%m-%d").to_string();
    let requirements = analysis.original_text.chars().take(150).collect::<String>();
    let concept_cap = capitalize(concept);
    
    format!(
        "// {} - Auto-generated by Carpai NLP Engine\n\
         // Generated at: {}\n\
         //\n\
         // Requirements:\n\
         // {}\n\
         \n\
         class {} {{\n\
             name: string;\n\
             version: string;\n\
             \n\
             constructor() {{\n\
                 this.name = \"{}\";\n\
                 this.version = \"1.0.0\";\n\
             }}\n\
             \n\
             run(): void {{\n\
                 console.log(`Starting ${{this.name}}...`);\n\
                 \n\
                 // TODO: Implement based on requirements\n\
                 // Original: {}\n\
             }}\n\
         }}\n\
         \n\
         function main(): void {{\n\
             const app = new {}();\n\
             app.run();\n\
         }}\n\
         \n\
         main();\n",
        concept,
        generated_date,
        requirements,
        concept_cap,
        concept_cap,
        concept,
        requirements,
        concept_cap
    )
}

/// Generate a Java project skeleton
pub fn generate_java_skeleton(analysis: &NlpAnalysisResult) -> String {
    const DEFAULT_CONCEPT: &str = "App";
    let concept = analysis.key_concepts.first().map(|s| s.as_str()).unwrap_or(DEFAULT_CONCEPT);
    let generated_date = chrono::Local::now().format("%Y-%m-%d").to_string();
    let requirements = analysis.original_text.chars().take(150).collect::<String>();
    let class_name = capitalize(concept);
    
    format!(
        "// {} - Auto-generated by Carpai NLP Engine\n\
         // Generated at: {}\n\
         //\n\
         // Requirements:\n\
         // {}\n\
         \n\
         public class {} {{\n\
             private String name;\n\
             private String version;\n\
             \n\
             public {}() {{\n\
                 this.name = \"{}\";\n\
                 this.version = \"1.0.0\";\n\
             }}\n\
             \n\
             public void run() {{\n\
                 System.out.println(\"Starting \" + name + \"...\");\n\
                 \n\
                 // TODO: Implement based on requirements\n\
                 // Original: {}\n\
             }}\n\
             \n\
             public static void main(String[] args) {{\n\
                 {} app = new {}();\n\
                 app.run();\n\
             }}\n\
         }}\n",
        concept,
        generated_date,
        requirements,
        class_name,
        class_name,
        concept,
        requirements,
        class_name,
        class_name
    )
}

/// Generate a C++ project skeleton
pub fn generate_cpp_skeleton(analysis: &NlpAnalysisResult) -> String {
    const DEFAULT_CONCEPT: &str = "app";
    let concept = analysis.key_concepts.first().map(|s| s.as_str()).unwrap_or(DEFAULT_CONCEPT);
    let generated_date = chrono::Local::now().format("%Y-%m-%d").to_string();
    let requirements = analysis.original_text.chars().take(150).collect::<String>();
    let class_name = capitalize(concept);
    
    format!(
        "// {} - Auto-generated by Carpai NLP Engine\n\
         // Generated at: {}\n\
         //\n\
         // Requirements:\n\
         // {}\n\
         \n\
         #include <iostream>\n\
         #include <string>\n\
         \n\
         class {} {{\n\
         private:\n\
             std::string name;\n\
             std::string version;\n\
             \n\
         public:\n\
             {}() : name(\"{}\"), version(\"1.0.0\") {{\n\
             }}\n\
             \n\
             void run() {{\n\
                 std::cout << \"Starting \" << name << \"...\\n\";\n\
                 \n\
                 // TODO: Implement based on requirements\n\
                 // Original: {}\n\
             }}\n\
         }};\n\
         \n\
         int main() {{\n\
             {} app;\n\
             app.run();\n\
             return 0;\n\
         }}\n",
        concept,
        generated_date,
        requirements,
        class_name,
        class_name,
        concept,
        requirements,
        class_name
    )
}

/// Generate a Python project skeleton
pub fn generate_python_skeleton(analysis: &NlpAnalysisResult) -> String {
    const DEFAULT_CONCEPT: &str = "app";
    let concept = analysis.key_concepts.first().map(|s| s.as_str()).unwrap_or(DEFAULT_CONCEPT);
    let generated_date = chrono::Local::now().format("%Y-%m-%d").to_string();
    let requirements = analysis.original_text.chars().take(150).collect::<String>();
    let concept_cap = capitalize(concept);
    
    format!(
        "# {} - Auto-generated by Carpai NLP Engine\n\
         # Generated at: {}\n\
         #\n\
         # Requirements:\n\
         # {}\n\
         \n\
         \"\"\"\n\
         {} module\n\
         \"\"\"\n\
         \n\
         import sys\n\
         from typing import Any, Optional\n\
         \n\
         class {}:\n\
             \"\"\"Main application class\"\"\"\n\
             \n\
             def __init__(self):\n\
                 self.name = \"{}\"\n\
                 self.version = \"1.0.0\"\n\
                 \n\
             def run(self) -> int:\n\
                 \"\"\"Run the main application\"\"\"\n\
                 print(f\"Starting {{self.name}}...\");\n\
                 \n\
                 # TODO: Implement based on requirements\n\
                 # Original: {}\n\
                 \n\
                 return 0\n\
         \n\
         def main() -> int:\n\
             app = {}()\n\
             return app.run()\n\
         \n\
         if __name__ == \"__main__\":\n\
             sys.exit(main())\n",
        concept,
        generated_date,
        requirements,
        concept,
        concept_cap,
        concept_cap,
        concept,
        requirements,
        concept_cap
    )
}

/// Generate a JavaScript/TypeScript project skeleton
pub fn generate_js_skeleton(analysis: &NlpAnalysisResult) -> String {
    generate_typescript_skeleton(analysis)
}

/// Generate a Go project skeleton
pub fn generate_go_skeleton(analysis: &NlpAnalysisResult) -> String {
    const DEFAULT_CONCEPT: &str = "main";
    let concept = analysis.key_concepts.first().map(|s| s.as_str()).unwrap_or(DEFAULT_CONCEPT);
    let generated_date = chrono::Local::now().format("%Y-%m-%d").to_string();
    let requirements = analysis.original_text.chars().take(200).collect::<String>();
    let concept_cap = capitalize(concept);
    
    format!(
        "// Package {} - Auto-generated by Carpai NLP Engine\n\
         //\n\
         // Generated at: {}\n\
         //\n\
         // Requirements:\n\
         // {}\n\
         \n\
         package main\n\
         \n\
         import (\n\
             \"fmt\"\n\
             \"log\"\n\
         )\n\
         \n\
         // {} represents the main application/component\n\
         type {} struct {{\n\
             Name string\n\
             Version string\n\
         }}\n\
         \n\
         // New creates a new instance of {}\n\
         func New() *{} {{\n\
             return &{} {{\n\
                 Name: \"{}\",\n\
                 Version: \"1.0.0\",\n\
             }}\n\
         }}\n\
         \n\
         // Run executes the main functionality\n\
         func (app *{}) Run() error {{\n\
             log.Println(\"Starting {}...\")\n\
             \n\
             // TODO: Implement based on requirements\n\
             // Original: {}\n\
             \n\
             return nil\n\
         }}\n\
         \n\
         func main() {{\n\
             app := New();\n\
             if err := app.Run(); err != nil {{\n\
                 log.Fatal(err)\n\
             }}\n\
         }}\n",
        concept,
        generated_date,
        requirements,
        concept_cap,
        concept_cap,
        concept_cap,
        concept_cap,
        concept_cap,
        concept_cap,
        concept_cap,
        concept_cap,
        concept,
        concept_cap,
        requirements
    )
}

/// Generate a usage example
pub fn generate_usage_example(language: &str) -> String {
    match language.to_lowercase().as_str() {
        "rust" => "cargo run".to_string(),
        "python" => "python main.py".to_string(),
        "javascript" | "typescript" => "node main.js".to_string(),
        "java" => "javac Main.java && java Main".to_string(),
        "c++" | "cpp" => "g++ main.cpp -o main && ./main".to_string(),
        "go" => "go run main.go".to_string(),
        _ => format!("Run the {} file", language),
    }
}

pub fn generate_dependencies(language: &str) -> Vec<DependencyInfo> {
    match language.to_lowercase().as_str() {
        "rust" => vec![
            DependencyInfo {
                name: "tokio".to_string(),
                version: Some("1.0".to_string()),
                package_manager: PackageManager::Cargo,
            },
            DependencyInfo {
                name: "serde".to_string(),
                version: Some("1.0".to_string()),
                package_manager: PackageManager::Cargo,
            },
        ],
        "python" => vec![
            DependencyInfo {
                name: "requests".to_string(),
                version: Some("2.31.0".to_string()),
                package_manager: PackageManager::Pip,
            },
        ],
        "javascript" | "typescript" => vec![
            DependencyInfo {
                name: "axios".to_string(),
                version: Some("1.6.0".to_string()),
                package_manager: PackageManager::Npm,
            },
        ],
        "go" => vec![
            DependencyInfo {
                name: "github.com/spf13/cobra".to_string(),
                version: Some("v1.7.0".to_string()),
                package_manager: PackageManager::GoMod,
            },
        ],
        _ => vec![],
    }
}
