use crate::nlp::types::*;
use crate::nlp::{DependencyInfo, PackageManager};

pub fn generate_rust_skeleton(analysis: &NlpAnalysisResult) -> String {
    format!(
        r#"//! {} - Auto-generated by CarpAI NLP Engine
//!
//! Generated at: {}
//!
//! ## Requirements Summary
//! - Classification: {}
//! - Intent: {}
//! - Complexity: {}
//! - Estimated Effort: {:?} days

use anyhow::Result;

/// Main entry point for {}
pub fn run() -> Result<()> {{
    println!("🚀 Starting {{}}...", include_str!(env!("CARGO_CRATE_NAME")));
    
    // TODO: Implement based on requirements
    // Original request: {{}}
    
    Ok(())
}}

#[cfg(test)]
mod tests {{
    #[test]
    fn test_skeleton_compiles() {{
        // Verify skeleton compiles
        assert!(true);
    }}
}}
"#,
        analysis.key_concepts.first().unwrap_or(&"Project".to_string()),
        chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
        analysis.classification,
        analysis.intent.primary,
        analysis.complexity.level,
        analysis.complexity.estimated_effort_days,
        analysis.key_concepts.first().unwrap_or(&"Project".to_string()),
    )
}

pub fn generate_typescript_skeleton(analysis: &NlpAnalysisResult) -> String {
    format!(
        r#"/**
 * {} - Auto-generated by CarpAI NLP Engine
 *
 * @generated {}
 * @description {}
 */

// Imports based on detected requirements
{{}}

/**
 * Main module for {}
 */
export class {} {{
    /**
     * Constructor
     */
    constructor() {{
        // Initialize
    }}
    
    /**
     * Execute main functionality
     */
    async run(): Promise<void> {{
        console.log('Starting {{}}...');
        
        // TODO: Implement based on requirements
        // Original: {{}}
    }}
}}

// Export default instance
export const app = new {{}};
export default app;
"#,
        analysis.key_concepts.first().unwrap_or(&"Module".to_string()),
        chrono::Local::now().format("%Y-%m-%d").to_string(),
        analysis.original_text.chars().take(100).collect::<String>(),
        analysis.key_concepts.first().unwrap_or(&"App".to_string()),
        analysis.key_concepts.first().unwrap_or(&"App".to_string())
    )
}

pub fn generate_java_skeleton(analysis: &NlpAnalysisResult) -> String {
    format!(
        r#"/**
 * {} - Auto-generated by CarpAI NLP Engine
 *
 * @author CarpAI NLP
 * @generated {}
 * @version 1.0.0
 */
package com.carpai.generated;

import java.util.*;
import java.util.concurrent.*;

/**
 * Main class for {}
 */
public class {} {{
    /**
     * Main entry point
     */
    public static void main(String[] args) {{
        System.out.println("Starting {}...");
        
        // TODO: Implement based on requirements
        // Original request: {}
    }}
    
    /**
     * Execute the main functionality
     */
    public void run() throws Exception {{
        // Implementation here
    }}
}}
"#,
        analysis.key_concepts.first().unwrap_or(&"Application".to_string()),
        chrono::Local::now().format("%Y-%m-%d").to_string(),
        analysis.key_concepts.first().unwrap_or(&"App".to_string()),
        analysis.key_concepts.first().unwrap_or(&"App".to_string()),
        analysis.original_text.chars().take(100).collect::<String>(),
        analysis.original_text.chars().take(50).collect::<String>()
    )
}

pub fn generate_cpp_skeleton(analysis: &NlpAnalysisResult) -> String {
    format!(
        r#"/**
 * @file {}
 * @brief Auto-generated by CarpAI NLP Engine
 * @date {}
 *
 * Description: {}
 */

#include <iostream>
#include <vector>
#include <string>
#include <memory>

// Using declarations
using namespace std;

namespace carpai_generated {{

/**
 * @class {}
 * @brief Main class for the generated solution
 */
class {} {{
public:
    /**
     * @brief Constructor
     */
    () : initialized_(false) {{
        // Initialize
    }}
    
    /**
     * @brief Run the main logic
     * @return 0 on success, non-zero on error
     */
    int run() {{
        std::cout << "Starting {}..." << std::endl;
        
        // TODO: Implement based on requirements
        // Original: {{}}
        
        return 0;
    }}

private:
    bool initialized_;
}};

}} // namespace carpai_generated

int main() {{
    carpai_generated::{} app;
    return app.run();
}}
"#,
        analysis.key_concepts.first().unwrap_or(&"solution".to_string()),
        analysis.key_concepts.first().unwrap_or(&"Solution".to_string()),
        chrono::Local::now().format("%Y-%m-%d").to_string(),
        analysis.original_text.chars().take(150).collect::<String>(),
        analysis.key_concepts.first().unwrap_or(&"Solution".to_string()),
        analysis.key_concepts.first().unwrap_or(&"Solution".to_string()),
        analysis.original_text.chars().take(100).collect::<String>()
    )
}

pub fn generate_go_skeleton(analysis: &NlpAnalysisResult) -> String {
    format!(
        r#">// Package {} - Auto-generated by Carpai NLP Engine
//
// Generated at: {}
//
// Requirements:
// {}

package main

import (
    "fmt",
    "log"
)

// {} represents the main application/component
type {} struct {{
    Name string
    Version string
}}

// New creates a new instance of {}
func New() *{} {{
    return &{}{{
        Name: "{}",
        Version: "1.0.0",
    }}
}}

// Run executes the main functionality
func (app *{}) Run() error {{
    log.Println("Starting {}...")
    
    // TODO: Implement based on requirements
    // Original: {}
    
    return nil
}}

func main() {{
    app := New()
    if err := app.Run(); err != nil {{
        log.Fatal(err)
    }}
}}
"#,
        analysis.key_concepts.first().unwrap_or(&"main".to_string()),
        chrono::Local::now().format("%Y-%m-%d").to_string(),
        analysis.original_text.chars().take(200).collect::<String>(),
        analysis.key_concepts.first().unwrap_or(&"App".to_string()),
        analysis.key_concepts.first().unwrap_or(&"App".to_string()),
        analysis.key_concepts.first().unwrap_or(&"App".to_string()),
        analysis.key_concepts.first().unwrap_or(&"App".to_string()),
        analysis.key_concepts.first().unwrap_or(&"App".to_string()),
        analysis.original_text.chars().take(100).collect::<String>(),
        analysis.original_text.chars().take(50).collect::<String>()
    )
}

pub fn generate_dependencies(language: &str) -> Vec<DependencyInfo> {
    match language.to_lowercase().as_str() {
        "rust" => vec![
            DependencyInfo {
                name: "tokio".to_string(),
                version: Some("1.0".to_string()),
                package_manager: PackageManager::Cargo,
            },
            DependencyInfo {
                name: "serde".to_string(),
                version: Some("1.0".to_string()),
                package_manager: PackageManager::Cargo,
            },
            DependencyInfo {
                name: "anyhow".to_string(),
                version: Some("1.0".to_string()),
                package_manager: PackageManager::Cargo,
            },
        ],
        "typescript" | "tsx" | "javascript" | "jsx" => vec![
            DependencyInfo {
                name: "typescript".to_string(),
                version: Some("^5.0.0".to_string()),
                package_manager: PackageManager::Npm,
            },
            DependencyInfo {
                name: "@types/node".to_string(),
                version: Some("^20.0.0".to_string()),
                package_manager: PackageManager::Npm,
            },
        ],
        "java" => vec![
            DependencyInfo {
                name: "org.slf4j:slf4j-api".to_string(),
                version: Some("2.0.7".to_string()),
                package_manager: PackageManager::Maven,
            },
            DependencyInfo {
                name: "junit:junit".to_string(),
                version: Some("5.9.1".to_string()),
                package_manager: PackageManager::Maven,
            },
        ],
        "c++" | "cpp" => vec![
            DependencyInfo {
                name: "nlohmann/json".to_string(),
                version: Some("3.11.2".to_string()),
                package_manager: PackageManager::Other("vcpkg/conan".to_string()),
            },
            DependencyInfo {
                name: "spdlog".to_string(),
                version: Some("1.12.0".to_string()),
                package_manager: PackageManager::Other("vcpkg/conan".to_string()),
            },
        ],
        "go" => vec![
            DependencyInfo {
                name: "github.com/gin-gonic/gin".to_string(),
                version: Some("v1.9.1".to_string()),
                package_manager: PackageManager::GoModules,
            },
            DependencyInfo {
                name: "github.com/sirupsen/logrus".to_string(),
                version: Some("v1.5.0".to_string()),
                package_manager: PackageManager::GoModules,
            },
        ],
        _ => vec![],
    }
}

pub fn generate_usage_example(language: &str) -> String {
    match language.to_lowercase().as_str() {
        "rust" => r#"# Usage Example

```rust
use my_app::run;

#[tokio::main]
async fn main() {
    if let Err(e) = run().await {
        eprintln!("Error: {}", e);
        std::process::exit(1);
    }
}
```
"#.to_string(),
        "typescript" => r#"# Usage Example

```typescript
import app from './app';

const client = new app();

// Run the application
client.run().catch(console.error);
```
"#.to_string(),
        "java" => r#"# Usage Example

```java
public class Main {
    public static void main(String[] args) {
        App app = new App();
        try {
            app.run();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
"#.to_string(),
        _ => format!("# Usage in {}\n\nTODO: Add usage example", language),
    }
}
