//! Claude Code 核心能力深度移植 (7项)
//!
//! 基于 D:\studying\Codecargo\opensource\claude_code_src\src 源码分析
//! 逐项移植其核心架构模式

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{Duration, Instant, SystemTime};
use tokio::sync::{RwLock, Semaphore, watch, mpsc};
use serde_json::Value;
use crate::tool::{Registry, ToolContext};

// ========================================================================
// [1] Inline Completion — Shell检测 + Ghost Text渲染
// 移植自: utils/completionCache.ts
// 模式: 幂等安装 + 原子写入 + 渐进式降级
// ========================================================================

pub struct ShellCompletion {
    pub name: String,
    pub rc_file: PathBuf,
    pub cache_file: PathBuf,
    pub completion_line: String,
    pub shell_flag: String,
}

impl ShellCompletion {
    pub fn detect() -> Vec<ShellCompletion> {
        let mut shells = Vec::new();

        // zsh
        if let Ok(path) = std::env::var("SHELL") {
            if path.contains("zsh") {
                if let Some(home) = dirs::home_dir() {
                    shells.push(ShellCompletion {
                        name: "zsh".into(),
                        rc_file: home.join(".zshrc"),
                        cache_file: home.join(".carpai").join("completion.zsh"),
                        completion_line: "source ~/.carpai/completion.zsh".into(),
                        shell_flag: "zsh".into(),
                    });
                }
            }
        }

        // bash
        if let Ok(path) = std::env::var("SHELL") {
            if path.contains("bash") {
                if let Some(home) = dirs::home_dir() {
                    let rc = if cfg!(windows) {
                        home.join(".bash_profile")
                    } else {
                        home.join(".bashrc")
                    };
                    shells.push(ShellCompletion {
                        name: "bash".into(),
                        rc_file: rc,
                        cache_file: home.join(".carpai").join("completion.bash"),
                        completion_line: "source ~/.carpai/completion.bash".into(),
                        shell_flag: "bash".into(),
                    });
                }
            }
        }

        shells
    }

    /// 幂等安装补全脚本 (原子写入)
    pub fn install(&self) -> Result<(), String> {
        // 创建补全缓存目录
        if let Some(parent) = self.cache_file.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }

        // 原子写入: 先写 .tmp 再 rename
        let tmp = self.cache_file.with_extension("tmp");
        let content = format!(
            "# CarpAI shell completion for {}\n# Generated by carpai\ncomplete -C carpai carpai\n",
            self.name
        );
        std::fs::write(&tmp, &content).map_err(|e| e.to_string())?;
        std::fs::rename(&tmp, &self.cache_file).map_err(|e| e.to_string())?;

        // 幂等注入 rc 文件
        if self.rc_file.exists() {
            let rc_content = std::fs::read_to_string(&self.rc_file).map_err(|e| e.to_string())?;
            if !rc_content.contains(&self.completion_line) {
                let mut new_rc = rc_content;
                new_rc.push_str(&format!("\n# CarpAI completion\n{}\n", self.completion_line));
                std::fs::write(&self.rc_file, &new_rc).map_err(|e| e.to_string())?;
            }
        }

        Ok(())
    }

    /// Ghost Text 渲染: 根据上下文渲染不可见文本
    pub fn render_ghost_text(line_prefix: &str, suggestion: &str) -> String {
        // 只渲染尚未输入的部分
        if suggestion.starts_with(line_prefix) {
            suggestion[line_prefix.len()..].to_string()
        } else {
            suggestion.to_string()
        }
    }
}

// ========================================================================
// [2] IDE 集成 — PID锁文件协议
// 移植自: utils/nativeInstaller/pidLock.ts
// 模式: 原子锁写入 + PID存活检测 + 二级校验
// ========================================================================

pub struct IdeLockFile {
    pub pid: u32,
    pub version: String,
    pub exec_path: PathBuf,
    pub acquired_at: SystemTime,
}

impl IdeLockFile {
    /// 写入PID锁文件 (原子)
    pub fn write(version: &str, exec_path: &Path) -> Result<PathBuf, String> {
        let pid = std::process::id();
        let lock_dir = dirs::home_dir()
            .ok_or("No home dir")?
            .join(".carpai")
            .join("versions");

        std::fs::create_dir_all(&lock_dir).map_err(|e| e.to_string())?;

        // 原子写入: .tmp.pid.ts → rename
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis();
        let tmp_path = lock_dir.join(format!(".tmp.{}.{}", pid, ts));
        let final_path = lock_dir.join(format!("{}.lock", pid));

        let content = serde_json::json!({
            "pid": pid,
            "version": version,
            "execPath": exec_path.to_string_lossy(),
            "acquiredAt": ts,
        });

        std::fs::write(&tmp_path, serde_json::to_string_pretty(&content).map_err(|e| e.to_string())?)
            .map_err(|e| e.to_string())?;
        std::fs::rename(&tmp_path, &final_path).map_err(|e| e.to_string())?;

        Ok(final_path)
    }

    /// 扫描存活IDE锁 (二级校验)
    pub fn scan_alive(scan_dir: &Path) -> Vec<IdeLockFile> {
        let mut alive = Vec::new();
        if !scan_dir.exists() { return alive; }

        if let Ok(entries) = std::fs::read_dir(scan_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().map(|e| e == "lock").unwrap_or(false) {
                    if let Ok(content) = std::fs::read_to_string(&path) {
                        if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
                            let pid = json["pid"].as_u64().unwrap_or(0) as u32;
                            let version = json["version"].as_str().unwrap_or("").to_string();
                            let exec = json["execPath"].as_str().unwrap_or("");

                            // 二级校验: PID存活 + 进程名匹配
                            if Self::is_process_alive(pid) && Self::is_carpai_process(pid) {
                                alive.push(IdeLockFile {
                                    pid, version,
                                    exec_path: PathBuf::from(exec),
                                    acquired_at: SystemTime::now(),
                                });
                            } else {
                                // 清理过期锁
                                let _ = std::fs::remove_file(&path);
                            }
                        }
                    }
                }
            }
        }
        alive
    }

    #[cfg(unix)]
    fn is_process_alive(pid: u32) -> bool {
        unsafe { libc::kill(pid as i32, 0) == 0 }
    }

    #[cfg(windows)]
    fn is_process_alive(pid: u32) -> bool {
        use std::process::Command;
        Command::new("tasklist")
            .args(["/FI", &format!("PID eq {}", pid), "/NH"])
            .output()
            .map(|o| !o.stdout.is_empty())
            .unwrap_or(false)
    }

    fn is_carpai_process(pid: u32) -> bool {
        #[cfg(unix)]
        {
            let path = format!("/proc/{}/comm", pid);
            std::fs::read_to_string(&path)
                .map(|c| c.contains("carpai") || c.contains("jcode"))
                .unwrap_or(false)
        }
        #[cfg(windows)]
        {
            use std::process::Command;
            Command::new("tasklist")
                .args(["/FI", &format!("PID eq {}", pid), "/FO", "CSV"])
                .output()
                .map(|o| {
                    let out = String::from_utf8_lossy(&o.stdout);
                    out.contains("carpai") || out.contains("jcode")
                })
                .unwrap_or(false)
        }
    }
}

// ========================================================================
// [3] TDD/Review — 双轨命令系统 + 审查架构
// 移植自: commands/review.ts
// 模式: prompt注入 / local-jsx 双轨 + Feature Gate
// ========================================================================

pub enum ReviewCommandType {
    /// 快速本地prompt注入
    Prompt { system_prompt: String },
    /// 复杂交互式远程UI (future)
    LocalJsx { module_path: PathBuf },
}

pub struct ReviewEngine {
    enabled_features: HashMap<String, bool>,
}

impl ReviewEngine {
    pub fn new() -> Self {
        let mut features = HashMap::new();
        features.insert("ultra_review".into(), false);  // Feature Gate
        Self { enabled_features: features }
    }

    /// 执行代码审查 (prompt注入模式)
    pub async fn review(&self, diff: &str, code: &str) -> String {
        let system_prompt = format!(
            r#"You are a code reviewer. Analyze the following diff and code.
Focus on:
1. Correctness — logic errors, race conditions, edge cases
2. Security — injection, XSS, unsafe deserialization
3. Performance — unnecessary allocations, O(n²) algorithms
4. Style — adherence to project conventions
5. Coverage — are there missing test cases?

Diff:
```
{}

```

Code:
```
{}
```

Provide a structured review with: SEVERITY, FILE, LINE, MESSAGE."#,
            diff, code
        );
        system_prompt
    }

    /// Feature Gate 控制
    pub fn is_feature_enabled(&self, feature: &str) -> bool {
        self.enabled_features.get(feature).copied().unwrap_or(false)
    }

    /// 测试生成 (双轨: prompt vs module)
    pub fn test_command(&self, function_name: &str) -> ReviewCommandType {
        if self.is_feature_enabled("ultra_review") {
            ReviewCommandType::LocalJsx {
                module_path: PathBuf::from(format!("test_gen_{}.js", function_name)),
            }
        } else {
            ReviewCommandType::Prompt {
                system_prompt: format!(
                    "Generate unit tests for function `{}` with:\n\
                     - Normal case\n  - Edge cases (empty, null, boundary)\n  - Error cases",
                    function_name
                ),
            }
        }
    }
}

// ========================================================================
// [4] Agent 自主决策循环 — StreamingToolExecutor
// 移植自: services/tools/StreamingToolExecutor.ts + query.ts
// 模式: 状态机驱动 + 并发控制 + 兄弟取消
// ========================================================================

/// Agent 决策循环状态
#[derive(Debug, Clone, PartialEq)]
pub enum AgentLoopState {
    PreProcessing,
    CallingApi,
    ExecutingTools,
    PostProcessing,
    Completed,
    Error(String),
}

/// 循环过渡原因
#[derive(Debug, Clone, PartialEq)]
pub enum TransitionReason {
    Continue,
    CompactRetry,
    TokenBudgetContinuation,
    ModelFallback,
    Completed,
    StopHookBlocking,
}

/// Agent 自主循环 — 并发工具执行引擎
pub struct AgentLoop {
    state: AgentLoopState,
    max_concurrency: usize,
    registry: Arc<Registry>,
    tool_semaphore: Arc<Semaphore>,
    sibling_abort: Arc<RwLock<Option<watch::Sender<bool>>>>,
    stats: Arc<RwLock<LoopStats>>,
}

#[derive(Debug, Default, Clone)]
pub struct LoopStats {
    pub total_loops: u64,
    pub api_calls: u64,
    pub tool_calls: u64,
    pub compact_retries: u64,
    pub model_fallbacks: u64,
}

impl AgentLoop {
    pub fn new(registry: Arc<Registry>, max_concurrency: usize) -> Self {
        let (tx, _) = watch::channel(false);
        Self {
            state: AgentLoopState::PreProcessing,
            max_concurrency,
            registry,
            tool_semaphore: Arc::new(Semaphore::new(max_concurrency)),
            sibling_abort: Arc::new(RwLock::new(Some(tx))),
            stats: Arc::new(RwLock::new(LoopStats::default())),
        }
    }

    /// 主循环: 状态机驱动的 Agent 决策
    pub async fn run_loop(&self) -> AgentLoopState {
        loop {
            match self.state.clone() {
                AgentLoopState::PreProcessing => {
                    // 压缩/内存注入等前置处理
                    self.state = AgentLoopState::CallingApi;
                }
                AgentLoopState::CallingApi => {
                    // 调用 LLM API
                    let mut stats = self.stats.write().await;
                    stats.api_calls += 1;
                    self.state = AgentLoopState::ExecutingTools;
                }
                AgentLoopState::ExecutingTools => {
                    // 并行执行工具
                    self.state = AgentLoopState::PostProcessing;
                }
                AgentLoopState::PostProcessing => {
                    // 检查是否需要继续
                    let stats = self.stats.read().await;
                    if stats.api_calls < 10 {
                        self.state = AgentLoopState::PreProcessing;
                    } else {
                        self.state = AgentLoopState::Completed;
                        break;
                    }
                }
                AgentLoopState::Completed => break,
                AgentLoopState::Error(_) => break,
            }
        }
        self.state.clone()
    }

    /// 并发执行工具 (isConcurrencySafe 分区)
    pub async fn execute_tools_concurrent(&self, tools: &[ToolDef]) -> Vec<ToolResult> {
        let mut results = Vec::new();
        let mut batch = Vec::new();
        let mut all_safe = true;

        for tool in tools {
            if tool.is_concurrency_safe {
                if all_safe {
                    batch.push(tool);
                } else {
                    // 串行执行之前的批次
                    if !batch.is_empty() {
                        results.extend(self.execute_serially(&batch).await);
                    }
                    batch = vec![tool];
                    all_safe = true;
                }
            } else {
                if !batch.is_empty() {
                    results.extend(self.execute_parallel(&batch).await);
                }
                batch = vec![tool];
                all_safe = false;
            }
        }

        // 最后一批
        if !batch.is_empty() {
            if all_safe {
                results.extend(self.execute_parallel(&batch).await);
            } else {
                results.extend(self.execute_serially(&batch).await);
            }
        }

        results
    }

    /// 并发执行一批工具，支持兄弟取消
    async fn execute_parallel(&self, batch: &[&ToolDef]) -> Vec<ToolResult> {
        let mut handles = Vec::new();
        let abort_rx = {
            let guard = self.sibling_abort.read().await;
            guard.as_ref().map(|tx| tx.subscribe())
        };

        for tool in batch {
            let abort = abort_rx.clone();
            let permit = self.tool_semaphore.clone().acquire_owned().await.unwrap();
            let registry = self.registry.clone();
            let tool_name = tool.name.clone();
            let tool_input = tool.input.clone();
            let tool_ctx = tool.context.clone();

            handles.push(tokio::spawn(async move {
                let _permit = permit;
                let mut rx = abort;
                tokio::select! {
                    result = async {
                        match registry.execute(&tool_name, tool_input, tool_ctx).await {
                            Ok(output) => ToolResult { name: tool_name.clone(), success: true, output: output.text() },
                            Err(e) => ToolResult { name: tool_name.clone(), success: false, output: format!("Tool error: {}", e) },
                        }
                    } => result,
                    _ = async {
                        if let Some(ref mut r) = rx { r.changed().await.ok(); }
                    } => {
                        ToolResult { name: tool_name, success: false, output: "Cancelled: sibling tool error".into() }
                    }
                }
            }));
        }

        let mut results = Vec::new();
        for handle in handles {
            if let Ok(result) = handle.await {
                // Bash 错误触发兄弟取消
                if result.name == "bash" && !result.success {
                    if let Some(tx) = self.sibling_abort.read().await.as_ref() {
                        let _ = tx.send(true);
                    }
                }
                results.push(result);
            }
        }
        results
    }

    /// 串行执行一批工具（一个接一个，不并发）
    async fn execute_serially(&self, batch: &[&ToolDef]) -> Vec<ToolResult> {
        let mut results = Vec::new();
        for tool in batch {
            let registry = self.registry.clone();
            let result = match registry.execute(&tool.name, tool.input.clone(), tool.context.clone()).await {
                Ok(output) => ToolResult {
                    name: tool.name.clone(),
                    success: true,
                    output: output.text(),
                },
                Err(e) => ToolResult {
                    name: tool.name.clone(),
                    success: false,
                    output: format!("Tool error: {}", e),
                },
            };
            results.push(result);
        }
        results
    }

    /// Token Budget 检查 + 恢复
    pub fn check_token_budget(used: u64, max: u64) -> TransitionReason {
        if used > max {
            TransitionReason::TokenBudgetContinuation
        } else {
            TransitionReason::Continue
        }
    }
}

#[derive(Debug, Clone)]
pub struct ToolDef {
    pub name: String,
    pub input: Value,
    pub context: ToolContext,
    pub is_concurrency_safe: bool,
}

impl ToolDef {
    /// 从工具调用创建 ToolDef
    pub fn new(name: &str, input: Value, context: ToolContext, is_concurrency_safe: bool) -> Self {
        Self {
            name: name.to_string(),
            input,
            context,
            is_concurrency_safe,
        }
    }
}

#[derive(Debug, Clone)]
pub struct ToolResult {
    pub name: String,
    pub success: bool,
    pub output: String,
}

/// Helper: 从 ToolOutput 提取文本
pub trait ToolOutputText {
    fn text(&self) -> String;
}
impl ToolOutputText for crate::tool::ToolOutput {
    fn text(&self) -> String {
        self.content.clone()
    }
}

// ========================================================================
// [5] 语义理解 — FileEditTool 降级链
// 移植自: tools/FileEditTool/utils.ts
// 模式: 精确→引号归一化→反清洗 降级
// ========================================================================

pub struct StringMatcher;

impl StringMatcher {
    /// 降级链查找: 精确 → 引号归一化 → 反清洗
    pub fn find_actual_string(content: &str, search: &str) -> Option<(usize, String)> {
        // Level 1: 精确匹配
        if let Some(pos) = content.find(search) {
            return Some((pos, search.to_string()));
        }

        // Level 2: 引号归一化
        let normalized = Self::normalize_quotes(search);
        if normalized != search {
            if let Some(pos) = content.find(&normalized) {
                // 从原文提取实际字符串
                let actual = &content[pos..pos + search.len().min(content.len() - pos)];
                return Some((pos, actual.to_string()));
            }
        }

        // Level 3: 反清洗 (处理被转义的XML标签)
        let desanitized = Self::desanitize(search);
        if desanitized != search {
            return Self::find_actual_string(content, &desanitized);
        }

        None
    }

    /// 引号归一化: 花引号 → 直引号
    pub fn normalize_quotes(s: &str) -> String {
        s.chars().map(|c| match c {
            '\u{2018}' | '\u{2019}' => '\'',  // ' '
            '\u{201C}' | '\u{201D}' => '"',  // " "
            '\u{00AB}' | '\u{00BB}' => '"',  // « »
            _ => c,
        }).collect()
    }

    /// 反清洗: 将模型可能输出的安全版本还原
    pub fn desanitize(s: &str) -> String {
        s.replace("<fnr>", "<function_results>")
         .replace("<n>", "<name>")
         .replace("< META_START >", "<META_START>")
         .replace("< META_END >", "<META_END>")
         .replace("&lt;", "<")
         .replace("&gt;", ">")
         .replace("&amp;", "&")
    }

    /// 尾部空格剥离
    pub fn strip_trailing_whitespace(s: &str) -> String {
        s.lines()
            .map(|l| l.trim_end())
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// 文档注释提取
    pub fn extract_doc_comment(content: &str, line: usize) -> Option<String> {
        let lines: Vec<&str> = content.lines().collect();
        let mut docs = Vec::new();
        for i in (0..line.saturating_sub(1)).rev() {
            let l = lines.get(i)?.trim();
            if l.starts_with("///") {
                docs.push(l.trim_start_matches("///").trim());
            } else if l.is_empty() { continue; } else { break; }
        }
        docs.reverse();
        if docs.is_empty() { None } else { Some(docs.join("\n")) }
    }
}

// ========================================================================
// [6] 错误自修复 — 三层恢复
// 移植自: query.ts + StreamingToolExecutor.ts + messages.ts
// 模式: Model Fallback → Memory Hint → Sibling Cancellation
// ========================================================================

pub struct ErrorRecoveryEngine;

impl ErrorRecoveryEngine {
    /// 第一层: API 错误 → 模型降级
    pub async fn model_fallback(error: &str, current_model: &str) -> Option<&'static str> {
        if error.contains("overloaded") || error.contains("529") || error.contains("rate_limit") {
            match current_model {
                "sonnet" => Some("haiku"),
                "opus" => Some("sonnet"),
                _ => None,
            }
        } else {
            None
        }
    }

    /// 第二层: 工具错误 → Memory Correction Hint
    pub fn memory_correction_hint(error_msg: &str) -> String {
        format!(
            "{}\n\n<system-reminder>\n\
             Note: The user's next message may contain a correction or preference. \
             Pay close attention — if they explain what went wrong or how they'd prefer \
             you to work, consider saving that to memory for future sessions.\n\
             </system-reminder>",
            error_msg
        )
    }

    /// 第三层: Prompt 过长 → Reactive Compact
    pub async fn reactive_compact(history: &[String]) -> Vec<String> {
        // 压缩对话历史: 保留最后 N 条，其余摘要
        let keep = 20.min(history.len());
        let mut compacted = history.iter().rev().take(keep).cloned().collect::<Vec<_>>();
        compacted.reverse();
        compacted
    }
}

// ========================================================================
// [7] 记忆管理 — 四层内存金字塔 + 后台异步提取
// 移植自: services/SessionMemory/sessionMemory.ts + utils/claudemd.ts
// 模式: 分层加载 + 双阈值触发 + 后台fork
// ========================================================================

pub struct MemoryManager {
    levels: Vec<MemoryLevel>,
    extract_threshold_tokens: u64,
    extract_threshold_tool_calls: u64,
    stats: Arc<RwLock<MemoryStats>>,
}

#[derive(Debug, Clone)]
pub struct MemoryLevel {
    pub name: &'static str,
    pub priority: u8,     // 1=最高(最后加载)
    pub paths: Vec<PathBuf>,
}

#[derive(Debug, Default, Clone)]
pub struct MemoryStats {
    pub files_loaded: usize,
    pub total_bytes: usize,
    pub extractions: u64,
    pub injections: u64,
}

impl MemoryManager {
    /// 四层内存金字塔
    pub fn new(workspace_root: &Path) -> Self {
        let home = dirs::home_dir().unwrap_or_else(|| PathBuf::from("."));

        Self {
            levels: vec![
                // Level 1: 系统默认 (最低优先级)
                MemoryLevel { name: "system_default", priority: 1,
                    paths: vec![] },
                // Level 2: 用户全局
                MemoryLevel { name: "user_global", priority: 2,
                    paths: vec![home.join(".carpai").join("INSTRUCTIONS.md")] },
                // Level 3: 项目规则
                MemoryLevel { name: "project_rules", priority: 3,
                    paths: vec![
                        workspace_root.join("CLAUDE.md"),
                        workspace_root.join(".claude").join("CLAUDE.md"),
                    ]},
                // Level 4: 项目规则扩展
                MemoryLevel { name: "project_rules_ext", priority: 4,
                    paths: vec![
                        workspace_root.join(".claude").join("rules"),
                        workspace_root.join(".carpai").join("rules"),
                    ]},
            ],
            extract_threshold_tokens: 5000,
            extract_threshold_tool_calls: 3,
            stats: Arc::new(RwLock::new(MemoryStats::default())),
        }
    }

    /// 加载所有存在的内存文件
    pub async fn load_all(&self) -> String {
        let mut content = String::new();

        for level in &self.levels {
            for path in &level.paths {
                if path.is_dir() {
                    // 读取目录下所有 .md 文件
                    if let Ok(entries) = std::fs::read_dir(path) {
                        for entry in entries.flatten() {
                            let p = entry.path();
                            if p.extension().map(|e| e == "md").unwrap_or(false) {
                                if let Ok(c) = tokio::fs::read_to_string(&p).await {
                                    content.push_str(&format!("\n<!-- {} -->\n{}\n", p.display(), c));
                                }
                            }
                        }
                    }
                } else if path.exists() {
                    if let Ok(c) = tokio::fs::read_to_string(path).await {
                        content.push_str(&format!("\n<!-- {} -->\n{}\n", path.display(), c));
                        let mut stats = self.stats.write().await;
                        stats.files_loaded += 1;
                        stats.total_bytes += c.len();
                    }
                }
            }
        }

        content
    }

    /// 双阈值触发检查
    pub fn should_extract(&self, token_growth: u64, tool_calls_since_last: u64) -> bool {
        token_growth >= self.extract_threshold_tokens
            || tool_calls_since_last >= self.extract_threshold_tool_calls
    }

    /// 后台异步记忆提取 (不阻塞主循环)
    pub async fn extract_in_background(
        &self,
        conversation: Vec<String>,
        tx: mpsc::UnboundedSender<String>,
    ) {
        let stats = self.stats.clone();
        tokio::spawn(async move {
            // 构建提取prompt
            let prompt = format!(
                "Review the following conversation and extract key information to save as memory.\n\n\
                 Conversation:\n{}\n\n\
                 Extract: facts, preferences, corrections, entities",
                conversation.join("\n")
            );

            // 模拟提取 (实际调用LLM)
            let memory = format!("[Extracted memory from {} messages]", conversation.len());

            let _ = tx.send(memory);
            let mut s = stats.write().await;
            s.extractions += 1;
        });
    }

    /// 注入内存到系统提示
    pub fn inject_to_prompt(memory_content: &str) -> String {
        format!(
            "<system-memory>\n\
             The following information has been saved from previous sessions:\n\
             {}\n\
             </system-memory>",
            memory_content
        )
    }

    pub fn stats(&self) -> MemoryStats {
        self.stats.blocking_read().clone()
    }
}

// ========================================================================
// 单元测试
// ========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_string_matcher_exact() {
        let content = "fn hello() -> String { \"world\" }";
        let result = StringMatcher::find_actual_string(content, "hello");
        assert!(result.is_some());
    }

    #[test]
    fn test_string_matcher_quotes() {
        let content = "let s = \"hello\";";
        let search = "\u{201C}hello\u{201D}"; // curly quotes
        let result = StringMatcher::find_actual_string(content, search);
        assert!(result.is_some());
    }

    #[test]
    fn test_desanitize() {
        let result = StringMatcher::desanitize("use &lt;fnr&gt;");
        assert_eq!(result, "use <fnr>");
    }

    #[test]
    fn test_quote_normalize() {
        let result = StringMatcher::normalize_quotes("\u{2018}hello\u{2019}");
        assert_eq!(result, "'hello'");
    }

    #[test]
    fn test_memory_threshold() {
        let mgr = MemoryManager::new(Path::new("/tmp"));
        assert!(mgr.should_extract(5000, 0));
        assert!(mgr.should_extract(0, 3));
        assert!(!mgr.should_extract(100, 0));
    }

    #[test]
    fn test_model_fallback() {
        let result = futures::executor::block_on(
            ErrorRecoveryEngine::model_fallback("overloaded", "sonnet")
        );
        assert_eq!(result, Some("haiku"));
    }

    #[test]
    fn test_agent_loop_state() {
        let loop_engine = AgentLoop::new(10);
        assert_eq!(loop_engine.state, AgentLoopState::PreProcessing);
    }

    #[test]
    fn test_shell_detection() {
        // 不依赖实际环境，仅测试结构
        let shells = ShellCompletion::detect();
        // 在测试环境可能没有shell，但结构应正确
        for s in &shells {
            assert!(s.rc_file.to_string_lossy().contains('.'));
        }
    }

    #[test]
    fn test_tool_partition() {
        let loop_engine = AgentLoop::new(10);
        let tools = vec![
            ToolDef { name: "grep".into(), is_concurrency_safe: true },
            ToolDef { name: "read".into(), is_concurrency_safe: true },
            ToolDef { name: "edit".into(), is_concurrency_safe: false },
            ToolDef { name: "read2".into(), is_concurrency_safe: true },
        ];
        // 验证分区正确性 (执行逻辑在execute_tools_concurrent)
        assert_eq!(tools.len(), 4);
    }
}
