/// Git 钩子配置
#[derive(Debug, Clone)]
pub struct HookConfig {
    pub hook_type: HookType,
    pub ci_config: crate::CiConfig,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HookType {
    PreCommit,
    PrePush,
    PostCommit,
}

/// Git 钩子管理器 — 安装/卸载/执行
pub struct GitHook;

impl GitHook {
    pub fn new() -> Self { Self }

    /// 安装指定类型的钩子
    pub fn install(config: &HookConfig) -> anyhow::Result<()> {
        match config.hook_type {
            HookType::PreCommit => Self::install_hook("pre-commit", config),
            HookType::PrePush => Self::install_hook("pre-push", config),
            HookType::PostCommit => Self::install_hook("post-commit", config),
        }
    }

    /// 安装 pre-push 钩子（向后兼容）
    pub fn install_pre_push(config: &HookConfig) -> anyhow::Result<()> {
        Self::install_hook("pre-push", config)
    }

    fn install_hook(hook_name: &str, config: &HookConfig) -> anyhow::Result<()> {
        let git_dir = std::path::Path::new(".git");
        if !git_dir.exists() {
            anyhow::bail!("Not a git repository");
        }

        let hook_path = git_dir.join("hooks").join(hook_name);
        let parallel_flag = if config.ci_config.parallel { "--parallel" } else { "" };
        let format_flag = format!("--format={}", config.ci_config.output_format);

        let hook_script = format!(
            r#"#!/bin/sh
# jcode Micro CI — {hook_name} hook
# Generated by jcode-micro-ci

jcode micro-ci check {parallel_flag} {format_flag}
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ jcode Micro CI failed. Fix errors before proceeding."
    exit 1
fi
"#,
            hook_name = hook_name,
            parallel_flag = parallel_flag,
            format_flag = format_flag,
        );

        std::fs::write(&hook_path, hook_script)?;
        // Make executable on Unix
        #[cfg(unix)]
        std::os::unix::fs::PermissionsExt::set_mode(
            &hook_path.metadata()?.permissions(),
            0o755,
        );

        println!("✅ jcode Micro CI {} hook installed at {:?}", hook_name, hook_path);
        Ok(())
    }

    /// 卸载钩子
    pub fn uninstall() -> anyhow::Result<()> {
        let hooks = ["pre-push", "pre-commit", "post-commit"];
        let mut count = 0;
        for hook_name in &hooks {
            let hook_path = std::path::Path::new(".git/hooks").join(hook_name);
            if hook_path.exists() {
                std::fs::remove_file(&hook_path)?;
                count += 1;
                println!("✅ Removed jcode Micro CI {} hook", hook_name);
            }
        }
        if count == 0 {
            println!("ℹ️ No jcode Micro CI hooks found");
        }
        Ok(())
    }
}
