# kube-prometheus-stack values for CarpAI
# Generated by Terraform - do not edit manually

prometheus:
  prometheusSpec:
    retention: ${prometheus_retention}
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: ${prometheus_storage}
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 8Gi
    additionalScrapeConfigs:
      - job_name: 'carpai'
        static_configs:
          - targets: ['carpai-server.${project_name}-${environment}.svc.cluster.local:9090']
        metrics_path: /metrics
        scrape_interval: 5s

alertmanager:
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  adminUser: ${grafana_admin_user}
  adminPassword: ${grafana_admin_password}
  persistence:
    enabled: true
    size: ${grafana_storage}
  defaultDashboardsEnabled: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: carpai
          orgId: 1
          folder: CarpAI
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/carpai
  dashboards:
    carpai:
      carpai-overview:
        url: https://raw.githubusercontent.com/juming75/CarpAI/main/deploy/grafana-dashboard-phase2.json
        token: ""
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://carpai-monitoring-prometheus.${project_name}-${environment}.svc.cluster.local:9090
          access: proxy
          isDefault: true
  ingress:
    enabled: ${enable_ingress}
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.${project_name}.${environment}.example.com
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.${project_name}.${environment}.example.com

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
