name: JCodeMobile
options:
  bundleIdPrefix: com.jcode
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

packages:
  JCodeKit:
    path: .

targets:
  JCodeMobile:
    type: application
    platform: iOS
    sources:
      - path: Sources/JCodeMobile
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: Sources/JCodeMobile/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jcode.mobile
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: JCodeKit
        product: JCodeKit
    entitlements:
      path: Sources/JCodeMobile/JCodeMobile.entitlements
      properties: {}
