apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "carpai.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "carpai.labels" . | nindent 4 }}
{{- if .Values.server.podAnnotations }}
  annotations:
    {{- toYaml .Values.server.podAnnotations | nindent 4 }}
{{- end }}
automountServiceAccountToken: true
