use std::collections::HashMap;

/// 脚手架配置
pub struct ScaffoldConfig {
    pub name: String,
    pub language: String,
    pub framework: String,
    pub with_docker: bool,
    pub with_swagger: bool,
    pub with_ci: bool,
    pub extra_files: HashMap<String, String>,
}

/// 生成的项目
#[derive(Debug, Clone)]
pub struct GeneratedProject {
    pub files: HashMap<String, String>,
    pub stats: ProjectStats,
}

#[derive(Debug, Clone, Default)]
pub struct ProjectStats {
    pub total_files: usize,
    pub code_lines: usize,
    pub config_files: usize,
}

/// 项目脚手架 — 生成代码 + 配置文件 + 文档
pub struct ProjectScaffolder {
    config: ScaffoldConfig,
}

impl ProjectScaffolder {
    pub fn new(config: ScaffoldConfig) -> Self { Self { config } }

    /// 生成完整项目结构
    pub async fn scaffold(&self, output_dir: &str) -> anyhow::Result<GeneratedProject> {
        let mut files = HashMap::new();

        // 1. 主代码
        files.extend(self.generate_main_code());

        // 2. Dockerfile
        if self.config.with_docker {
            files.insert("Dockerfile".into(), self.generate_dockerfile());
            files.insert(".dockerignore".into(), self.generate_dockerignore());
        }

        // 3. Swagger/OpenAPI 文档
        if self.config.with_swagger {
            files.insert("openapi.yaml".into(), self.generate_swagger());
        }

        // 4. CI/CD 配置 (委托给 jcode-ci-generator)
        if self.config.with_ci {
            files.insert(".gitlab-ci.yml".into(), self.generate_gitlab_ci());
        }

        // 5. 额外文件
        files.extend(self.config.extra_files.clone());

        // 写入磁盘
        let output = std::path::Path::new(output_dir);
        for (path, content) in &files {
            let full_path = output.join(path);
            if let Some(parent) = full_path.parent() {
                tokio::fs::create_dir_all(parent).await?;
            }
            tokio::fs::write(&full_path, content).await?;
        }

        let stats = ProjectStats {
            total_files: files.len(),
            code_lines: files.values().map(|c| c.lines().count()).sum(),
            config_files: if self.config.with_ci { 1 } else { 0 }
                + if self.config.with_docker { 2 } else { 0 }
                + if self.config.with_swagger { 1 } else { 0 },
        };

        Ok(GeneratedProject { files, stats })
    }

    fn generate_main_code(&self) -> HashMap<String, String> {
        let mut files = HashMap::new();
        let name = &self.config.name;

        match self.config.language.as_str() {
            "rust" => {
                files.insert("Cargo.toml".into(), format!(r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
"#));
                files.insert("src/main.rs".into(), format!(r#"fn main() {{
    println!("Hello from {name}!");
}}
"#));
                files.insert("src/lib.rs".into(), format!(r#"pub fn greet() -> &'static str {{
    "Hello from {name}!"
}}
"#));
            }
            "typescript" | "javascript" => {
                files.insert("package.json".into(), format!(r#"{{
  "name": "{name}",
  "version": "1.0.0",
  "scripts": {{ "start": "node dist/index.js", "build": "tsc", "test": "jest" }},
  "dependencies": {{ "express": "^4" }}
}}"#));
                files.insert("tsconfig.json".into(), r#"{ "compilerOptions": { "target": "ES2020", "module": "commonjs", "outDir": "./dist", "strict": true } }"#.into());
                files.insert("src/index.ts".into(), format!(r#"import express from 'express';
const app = express();
app.get('/', (_, res) => res.send('{name}'));
app.listen(3000);
"#));
            }
            "python" => {
                files.insert("requirements.txt".into(), "fastapi\nuvicorn\n".into());
                files.insert("main.py".into(), format!(r#"from fastapi import FastAPI

app = FastAPI(title="{name}")

@app.get("/")
def read_root():
    return {{"message": "{name}"}}
"#));
            }
            _ => {
                files.insert("README.md".into(), format!("# {name}\n\nAuto-generated by jcode-project-builder\n"));
            }
        }
        files
    }

    fn generate_dockerfile(&self) -> String {
        let (base_image, build_cmd, _run_base, run_cmd) = match self.config.language.as_str() {
            "rust" => ("rust:1.78-slim AS builder", "cargo build --release",
                       "debian:bookworm-slim", "./target/release/app"),
            "typescript" | "javascript" => ("node:20-alpine AS builder", "npm run build",
                                            "node:20-alpine", "node dist/index.js"),
            "python" => ("python:3.12-slim", "pip install -r requirements.txt",
                         "python:3.12-slim", "uvicorn main:app --host 0.0.0.0"),
            _ => ("ubuntu:22.04", "echo build", "ubuntu:22.04", "echo run"),
        };

        let run_base = run_cmd;
        format!(r#"# jcode-auto-generated Dockerfile
FROM {base_image} AS builder
WORKDIR /app
COPY . .
RUN {build_cmd}

FROM {run_base}
WORKDIR /app
COPY --from=builder /app/target/release/app /app/app
EXPOSE 3000
CMD ["{run_cmd}"]
"#, build_cmd = build_cmd, run_cmd = run_cmd, run_base = run_base,
            base_image = base_image)
    }

    fn generate_dockerignore(&self) -> String {
        "target/\nnode_modules/\n.git/\n*.md\n".into()
    }

    fn generate_swagger(&self) -> String {
        format!(r#"openapi: "3.0.0"
info:
  title: {}
  version: "1.0.0"
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        "200":
          description: OK
"#, self.config.name)
    }

    fn generate_gitlab_ci(&self) -> String {
        format!(r#"# jcode-auto-generated .gitlab-ci.yml
image: {image}
stages:
  - build
  - test
build:
  stage: build
  script: {build}
test:
  stage: test
  script: {test}
"#, 
            image = match self.config.language.as_str() {
                "rust" => "rust:latest",
                "typescript" | "javascript" => "node:20-alpine",
                "python" => "python:3.12-slim",
                _ => "ubuntu:22.04",
            },
            build = match self.config.language.as_str() {
                "rust" => "- cargo build --release",
                "typescript" => "- npm run build",
                "python" => "- echo 'no build step'",
                _ => "- echo build",
            },
            test = match self.config.language.as_str() {
                "rust" => "- cargo test",
                "typescript" => "- npm test",
                "python" => "- pytest",
                _ => "- echo test",
            },
        )
    }
}
