@echo off
REM jcode Quick Install Script for Windows
REM Like Cursor's installer - download, configure, start!

setlocal EnableDelayedExpansion

echo ========================================
echo   jcode AI Coding Assistant Installer
echo   (Open-Source Cursor Alternative)
echo ========================================
echo.

REM Check prerequisites
echo [1/6] Checking system requirements...

where python >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo ❌ Python not found. Please install Python 3.8+
    echo    Download: https://www.python.org/downloads/
    pause
    exit /b 1
)

python --version >nul 2>&1
for /f "tokens=2 delims= " %%v in ('python --version 2^>^&1') do set PYTHON_VERSION=%%v)
echo ✅ Found Python %PYTHON_VERSION%

REM Check Rust toolchain (optional, for building from source)
where cargo >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    for /f "tokens=3 delims= " %%v in ('cargo --version') do set CARGO_VERSION=%%v)
    echo ✅ Found Cargo %CARGO_VERSION%
) else (
    echo ⚠️  Rust/Cargo not found. Will use pre-built binaries if available.
)

echo.

REM Detect VS Code installation
echo [2/6] Detecting VS Code...
if exist "%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe" (
    set VSCODE_PATH=%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe
    echo ✅ VS Code found at: %VSCODE_PATH%
) else if exist "%ProgramFiles%\Microsoft VS Code\Code.exe" (
    set VSCODE_PATH=%ProgramFiles%\Microsoft VS Code\Code.exe
    echo ✅ VS Code found at: %VSCODE_PATH%
) else (
    echo ⚠️  VS Code not found. jcode will still work but IDE integration limited.
    set VSCODE_PATH=
)

echo.

REM Create configuration directory
echo [3/6] Creating configuration directory...

if not exist "%USERPROFILE%\.jcode" (
    mkdir "%USERPROFILE%\.jcode"
    echo ✅ Created ~/.jcode/
) else (
    echo ℹ️  Configuration directory already exists
)

if not exist "%USERPROFILE%\.jcode\logs" (
    mkdir "%USERPROFILE%\.jcode\logs"
)

echo.

REM Check for API keys
echo [4/6] Checking API keys...

set HAS_API_KEY=0

if defined DEEPSEEK_API_KEY (
    if not "%DEEPSEEK_API_KEY%"=="" (
        set HAS_API_KEY=1
        echo ✅ DEEPSEEK_API_KEY found in environment
    )
)

if defined OPENAI_API_KEY (
    if not "%OPENAI_API_KEY%"=="" (
        set HAS_API_KEY=1
        echo ✅ OPENAI_API_KEY found in environment
    )
)

if %HAS_API_KEY% EQU 0 (
    echo.
    echo ⚠️  No API key detected!
    echo.
    echo To use jcode with cloud providers, set one of:
    echo   set DEEPSEEK_API_KEY=your-key-here
    echo   set OPENAI_API_KEY=your-key-here
    echo.
    echo Or edit %%USERPROFILE%%\.jcode\config.toml later
    echo.
    echo For now, we'll configure for local-only mode or you can add the key later.
)

echo.

REM Generate default configuration
echo [5/6] Generating smart default config...

(
echo # jcode Configuration File
echo # Generated by installer on %date% %time%
echo.
echo [llm]
echo # Auto-detect provider based on available API keys
echo default_provider = "deepseek"
echo default_model = "deepseek-chat"
echo auto_detect_api_key = true
echo timeout_secs = 30
echo max_retries = 3
echo.
echo [grpc]
echo address = "[::]"
echo port = 50051
echo.
echo [rest]
echo address = "127.0.0.1"
echo port = 3000
echo enable_docs = true
echo.
echo [rag]
echo enabled = true
echo max_retrieved_snippets = 8
echo.
echo [vscode]
echo auto_detect = true
echo inline_completion_enabled = true
echo chat_panel_enabled = true
echo terminal_integration = true
echo.
echo [performance]
echo worker_threads = 4
echo stream_buffer_size = 4096
echo enable_cache = true
echo.
echo [logging]
echo level = "info"
echo log_requests = true
) > "%USERPROFILE%\.jcode\config.toml"

echo ✅ Configuration saved to %USERPROFILE%\.jcode\config.toml

echo.

REM Download or build jcode
echo [6/6] Setting up jcode binary...

if exist "%LOCALAPPDATA%\jcode\bin\jcode.exe" (
    echo ✅ jcode binary already installed
    set JCODE_BINARY=%LOCALAPPDATA%\jcode\bin\jcode.exe
) else (
    echo Downloading pre-built jcode binary...
    
    REM Try to download from GitHub releases (placeholder URL)
    echo ⚠️  Pre-built binaries not yet available.
    echo    You can build from source:
    echo      git clone https://github.com/jcode-dev/jcode.git
    echo      cd jcode
    echo      cargo build --release
    echo.
    echo    Or wait for official release binaries.
    
    set JCODE_BINARY=jcode
)

echo.
echo ========================================
echo   Installation Complete! 🎉
echo ========================================
echo.
echo Next steps:
echo.
echo 1. Start jcode server:
echo    jcode-server start
echo.
echo 2. Open VS Code and install extension:
echo    ext install jcode.jcode
echo    (or build from vscode-extension/ folder)
echo.
echo 3. Configure your API key (if using cloud):
echo    - Set DEEPSEEK_API_KEY environment variable
echo    - Or edit %%USERPROFILE%%\.jcode\config.toml
echo.
echo 4. Enjoy! Press Alt+\ for inline completions
echo.
echo ========================================
echo.
echo For help and documentation:
echo   https://github.com/jcode-dev/jcode
echo   https://docs.jcode.dev
echo.

pause
endlocal
