#!/bin/bash
# jcode Quick Install Script for Linux/macOS
# Like Cursor's installer - download, configure, start!

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  jcode AI Coding Assistant Installer${NC}"
echo -e "${BLUE}  (Open-Source Cursor Alternative)${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Step 1: Check prerequisites
echo -e "[1/6] ${YELLOW}Checking system requirements...${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ Python3 not found${NC}"
    echo "   Please install Python 3.8+"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | awk '{print $2}')
echo -e "${GREEN}✅ Found Python ${PYTHON_VERSION}${NC}"

# Check Rust (optional)
if command -v cargo &> /dev/null; then
    CARGO_VERSION=$(cargo --version | awk '{print $2}')
    echo -e "${GREEN}✅ Found Cargo ${CARGO_VERSION}${NC}"
else
    echo -e "${YELLOW}⚠️  Rust/Cargo not found (optional)${NC}"
fi

# Step 2: Detect VS Code
echo ""
echo -e "[2/6] ${YELLOW}Detecting VS Code...${NC}"

VSCODE_PATH=""
if command -v code &> /dev/null; then
    VSCODE_PATH=$(which code)
    echo -e "${GREEN}✅ VS Code found at: ${VSCODE_PATH}${NC}"
elif [ -d "/Applications/Visual Studio Code.app" ]; then
    VSCODE_PATH="/Applications/Visual Studio Code.app"
    echo -e "${GREEN}✅ VS Code found at: ${VSCODE_PATH}${NC}"
elif [ -d "/usr/bin/code" ]; then
    VSCODE_PATH="/usr/bin/code"
    echo -e "${GREEN}✅ VS Code found at: ${VSCODE_PATH}${NC}"
else
    echo -e "${YELLOW}⚠️  VS Code not found${NC}"
    echo "   jcode will work without it, but IDE integration will be limited."
fi

# Step 3: Create configuration directory
echo ""
echo -e "[3/6] ${YELLOW}Creating configuration directory...${NC}"

JCODE_HOME="$HOME/.jcode"

if [ ! -d "$JCODE_HOME" ]; then
    mkdir -p "$JCODE_HOME"
    mkdir -p "$JCODE_HOME/logs"
    echo -e "${GREEN}✅ Created ${JCODE_HOME}/${NC}"
else
    echo -e "${BLUE}ℹ️  ${JCODE_HOME}/ already exists${NC}"
fi

# Step 4: Check for API keys
echo ""
echo -e "[4/6] ${YELLOW}Checking API keys...${NC}"

HAS_API_KEY=0

if [ -n "$DEEPSEEK_API_KEY" ]; then
    echo -e "${GREEN}✅ DEEPSEEK_API_KEY found${NC}"
    HAS_API_KEY=1
fi

if [ -n "$OPENAI_API_KEY" ]; then
    echo -e "${GREEN}✅ OPENAI_API_KEY found${NC}"
    HAS_API_KEY=1
fi

if [ $HAS_API_KEY -eq 0 ]; then
    echo ""
    echo -e "${YELLOW}⚠️  No API key detected!${NC}"
    echo ""
    echo "To use jcode with cloud providers:"
    echo "  export DEEPSEEK_API_KEY='your-key-here'"
    echo "  export OPENAI_API_KEY='your-key-here'"
    echo ""
    echo "Or edit ${JCODE_HOME}/config.toml after installation"
    echo ""
    echo "For now, configuring for local mode..."
fi

# Step 5: Generate smart default configuration
echo ""
echo -e "[5/6] ${YELLOW}Generating optimized config...${NC}"

cat > "$JCODE_HOME/config.toml" << 'EOF'
# jcode Configuration File
# Generated by installer

[llm]
default_provider = "deepseek"
default_model = "deepseek-chat"
auto_detect_api_key = true
timeout_secs = 30
max_retries = 3

[grpc]
address = "[::]"
port = 50051

[rest]
address = "127.0.0.1"
port = 3000
enable_docs = true

[rag]
enabled = true
max_retrieved_snippets = 8

[vscode]
auto_detect = true
inline_completion_enabled = true
chat_panel_enabled = true
terminal_integration = true

[performance]
worker_threads = 4
stream_buffer_size = 4096
enable_cache = true

[logging]
level = "info"
log_requests = true
EOF

echo -e "${GREEN}✅ Config saved to ${JCODE_HOME}/config.toml${NC}"

# Step 6: Setup binary
echo ""
echo -e "[6/6] ${YELLOW}Setting up jcode binary...${NC}"

JCODE_BIN="${HOME}/.local/bin/jcode"

if [ -f "$JCODE_BIN" ]; then
    echo -e "${GREEN}✅ jcode binary already installed${NC}"
else
    echo "Checking for pre-built binary..."
    
    # Placeholder: In future, download from releases
    echo -e "${YELLOW}⚠️  Pre-built binaries not yet available${NC}"
    echo ""
    echo "Options:"
    echo "  1. Build from source:"
    echo "     git clone https://github.com/jcode-dev/jcode.git"
    echo "     cd jcode && cargo build --release"
    echo ""
    echo "  2. Wait for official release"
    echo ""
    
    # Add to PATH via symlink (when built)
    if [ ! -d "$HOME/.local/bin" ]; then
        mkdir -p "$HOME/.local/bin"
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.zshrc"
    fi
    
    JCODE_BIN="jcode"
fi

# Print summary
echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}  Installation Complete! 🎉${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Next steps:"
echo ""
echo " 1. Start jcode server:"
echo "     ${JCODE_BIN} server start"
echo ""
echo " 2. Install VS Code extension:"
if [ -n "$VSCODE_PATH" ]; then
    echo "     code --install-extension jcode.jcode"
    echo "     (or build from vscode-extension/ folder)"
else
    echo "     First install VS Code, then run above command"
fi
echo ""
echo " 3. Configure API key (for cloud usage):"
echo "     export DEEPSEEK_API_KEY='your-key'"
echo "     # or edit ${JCODE_HOME}/config.toml"
echo ""
echo " 4. Enjoy! Press Alt+\\ for inline completions"
echo ""
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Documentation: https://github.com/jcode-dev/jcode"
echo "Support: https://docs.jcode.dev"
echo ""

# Ask if user wants to start server now
read -p "Start jcode server now? [y/N] " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Starting jcode server..."
    if [ -f "$JCODE_BIN" ] && [ -x "$JCODE_BIN" ]; then
        "$JCODE_BIN" server start &
        sleep 2
        echo -e "${GREEN}✅ Server started in background${NC}"
        echo "   gRPC: localhost:50051"
        echo "   REST: http://localhost:3000"
    else
        echo -e "${YELLOW}⚠️  Binary not found yet. Build first:${NC}"
        echo "  cd path/to/jcode && cargo build --release"
    fi
fi

echo ""
echo "Thank you for installing jcode! 🚀"
