#!/usr/bin/env python3
"""更新src/tool/mod.rs以包含所有新工具模块"""

import os
from pathlib import Path

def main():
    tool_dir = Path("src/tool")
    mod_file = tool_dir / "mod.rs"

    # 获取所有.rs文件（排除mod.rs和tests文件）
    tool_files = [f.stem for f in tool_dir.glob("*.rs")
                  if f.stem not in ['mod', 'tests'] and not f.stem.endswith('_tests')]

    tool_files.sort()

    # 生成mod声明
    mod_declarations = []
    for tool in tool_files:
        mod_declarations.append(f"pub mod {tool};")

    # 读取现有内容
    if mod_file.exists():
        existing_content = mod_file.read_text(encoding='utf-8')
    else:
        existing_content = ""

    # 保留原有的非mod行（如use语句、函数等）
    non_mod_lines = []
    for line in existing_content.split('\n'):
        stripped = line.strip()
        if not stripped.startswith('mod ') and not stripped.startswith('//') and stripped:
            non_mod_lines.append(line)

    # 构建新内容
    new_content = "// Auto-generated module declarations\n"
    new_content += "// Generated by scripts/update_tool_mod.py\n\n"
    new_content += '\n'.join(mod_declarations)
    new_content += '\n\n'

    # 添加原有的非mod内容
    if non_mod_lines:
        new_content += '\n'.join(non_mod_lines)

    mod_file.write_text(new_content, encoding='utf-8')
    print(f"Updated mod.rs with {len(tool_files)} module declarations")


if __name__ == "__main__":
    main()
